<a href="https://colab.research.google.com/github/LeandroCoelhos/estudos_datascience/blob/main/Share_Derivativos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
def montar_df(periodo, valor, banco, tipo):
  df = pd.DataFrame()
  df['periodo'] = periodo
  df['valor'] = valor
  df['banco'] = banco
  df['tipo'] = tipo
  return df

In [ ]:
 #Itau derivativos
periodo = [202212, 202303, 202306, 202309, 202312]
valor = [78.341, 88.687, 72.773, 68.730, 56.383]
df = montar_df(periodo, valor, 'itau', 'atv')

In [ ]:
#Itau derivativos
valor = [78.512, 84.582, 68.027, 64.087, 53.495]
df_aux = montar_df(periodo, valor, 'itau', 'pas')

In [ ]:
df = pd.concat([df, df_aux], axis=0)

In [ ]:
# Bradesco
valores = [16.591, 28.207, 23.513, 22.870, 15.492]
df_aux = montar_df(periodo, valor, 'bradesco', 'atv')

df = pd.concat([df, df_aux], axis=0)
valores = [11.536, 24.043, 21.856, 19.936, 13.835]
df_aux = montar_df(periodo, valor, 'bradesco', 'pas')
df = pd.concat([df, df_aux], axis=0)

In [ ]:
# XP
periodo = [202309, 202312]
valores = [19.815, 23.733]
df_aux = montar_df(periodo, valor, 'bradesco', 'atv')
df = pd.concat([df, df_aux], axis=0)

periodo = [202309, 202312]
valores = [19.815, 23.733]
valores = [11.536, 24.043, 21.856, 19.936, 13.835]
df_aux = montar_df(periodo, valor, 'bradesco', 'pas')
df = pd.concat([df, df_aux], axis=0)

In [ ]:
# Santander
valores = [16.591, 28.207, 23.513, 22.870, 15.492]
df_aux = montar_df(periodo, valor, 'bradesco', 'atv')

df = pd.concat([df, df_aux], axis=0)
valores = [11.536, 24.043, 21.856, 19.936, 13.835]
df_aux = montar_df(periodo, valor, 'bradesco', 'pas')
df = pd.concat([df, df_aux], axis=0)

In [ ]:
df

   periodo   valor     banco tipo
0   202212  78.341      itau  atv
1   202303  88.687      itau  atv
2   202306  72.773      itau  atv
3   202309  68.730      itau  atv
4   202312  56.383      itau  atv
0   202212  78.512      itau  pas
1   202303  84.582      itau  pas
2   202306  68.027      itau  pas
3   202309  64.087      itau  pas
4   202312  53.495      itau  pas
0   202212  78.512  bradesco  atv
1   202303  84.582  bradesco  atv
2   202306  68.027  bradesco  atv
3   202309  64.087  bradesco  atv
4   202312  53.495  bradesco  atv
0   202212  78.512  bradesco  pas
1   202303  84.582  bradesco  pas
2   202306  68.027  bradesco  pas
3   202309  64.087  bradesco  pas
4   202312  53.495  bradesco  pas